title: OpenAI API Storytelling Lessons
description: A structured series of lessons on the OpenAI API.
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

url: "https://oxeg.github.io"
baseurl: "/openaiapi"
github:
  is_project_page: true
  repository_url: https://github.com/oxeg/openaiapi
